export const ADD_MESSAGE="ADD_MESSAGE"
export const SET_SELECTED_MESSAGE = 'SET_SELECTED_MESSAGE'
export const REMOVE_MESSAGE ='REMOVE_MESSAGE'
export const SET_COMPOSE_WINDOW_STATE='SET_COMPOSE_WINDOW_STATE'